pipeline:
  name: packer-test-aws
  identifier: packertestaws
  projectIdentifier: Testpackeraws
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: manikantagit
        repoName: Ansibleproject
        build: <+input>
  stages:
    - stage:
        name: test-aws
        identifier: testaws
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: |-
                      wget https://releases.hashicorp.com/packer/latest/packer_1.11.2_linux_amd64.zip # Replace with the latest version
                      unzip packer_1.11.2_linux_amd64.zip
                      sudo mv packer /usr/local/bin/
                      packer --version
                      cd /path/to/your/packer/code
                      packer build aws1.pkr.hcl
